var c_card = document.getElementById('coin_card');
c_card.style.position = 'absolute';
c_card.style.top = '50px';
c_card.style.left = '50px';
c_card.style.height = '550px';
c_card.style.width = '400px';
c_card.style.borderRadius = '25px';
c_card.style.boxShadow= 'inset 0 0 20px rgba(0,0,0,0.2)';
var coin_card = document.createElement('div');
var text_area = document.createElement('h1');
text_area.style.textAlign = "center";
text_area.innerHTML = 'Flip the coin';
coin_card.style.width = '400px';
coin_card.style.height = '400px';
var coin = document.createElement('div');
var line = document.createElement('hr');
line.style.width = '90%';
coin.style.position = 'absolute';
coin.style.top = '50px';
coin.style.left = '50px';
coin.style.height = '300px';
coin.style.width = '300px';
coin.style.align = 'center';
coin.style.borderRadius = '150px';
coin.style.backgroundColor = '#222222';
c_card.appendChild(coin_card);
coin_card.appendChild(coin);
c_card.appendChild(line);
c_card.appendChild(text_area);

